from .multiShapeletLib import *   # generated by SWIG
from .version import *   # generated by sconsUtils unless you tell it not to

import lsst.pex.config
import lsst.meas.algorithms

@lsst.pex.config.wrap(HybridOptimizerControl)
class HybridOptimizerConfig(lsst.pex.config.Config):
    pass

lsst.meas.algorithms.AlgorithmRegistry.register("multishapelet.psf", FitPsfControl)

del lsst # cleanup namespace
