# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.pybind11(["constants/constants",
                                  "shapeletFunction/shapeletFunction",
                                  "gaussHermiteProjection",
                                  "gaussHermiteConvolution",
                                  "multiShapeletFunction/multiShapeletFunction",
                                  "multiShapeletBasis",
                                  "matrixBuilder",
                                  "hermiteTransformMatrix",
                                  "radialProfile/radialProfile",
                                  "functorKeys",
                                  "basisEvaluator"], addUnderscore=False)
