# -*- python -*-
from lsst.sconsUtils import scripts
scripts.BasicSConscript.python(['_shapeletLib'], [
    '_shapeletLib.cc',
    'constants/constants.cc',
    'shapeletFunction/shapeletFunction.cc',
    'gaussHermiteProjection.cc',
    'gaussHermiteConvolution.cc',
    'multiShapeletFunction/multiShapeletFunction.cc',
    'multiShapeletBasis.cc',
    'matrixBuilder.cc',
    'hermiteTransformMatrix.cc',
    'radialProfile/radialProfile.cc',
    'functorKeys.cc',
    'basisEvaluator.cc'])
